### ISSUE TITLE
Django 5+Support

### ISSUE THREAD

**Issue by APPIAHTECH** [HiroshiFuu/django4-inline-actions#3]
Hi everyone,

Hope you're all doing well!

I'm using the latest Django version, Django 5.0.6, and I've encountered an issue:

- ERROR: Cannot install -r requirements.txt
- Django==5.0.6 because these package versions have conflicting dependencies.
- `django4-inline-actions 1.7 depends on django<4.3 and >=3.0`

@HiroshiFuu, do you plan to release a version compatible with Django 5+?

Thanks!

**Comment by HiroshiFuu** [comment]
Actually, yes. And actually, I plan to upgrade it when Django 5.1 is released. But never mind, I will test it with Django 5.0 tomorrow or the day after tomorrow.

**Comment by APPIAHTECH** [comment]
Any updates?

**Comment by HiroshiFuu** [comment]
> Any updates?

Sorry for the late replay, I have added Django 5 in version 1.8.

https://pypi.org/project/django4-inline-actions/

**Comment by APPIAHTECH** [comment]
Thanks @HiroshiFu 🦾
